CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(128) NOT NULL UNIQUE,
    password_hash VARCHAR(200) NOT NULL,
    name VARCHAR(200) NOT NULL,
    role VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(300) NOT NULL,
    description VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT NOT NULL,
    text VARCHAR(4000) NOT NULL,
    options_json CLOB,
    correct_answer CLOB NOT NULL,
    difficulty DOUBLE PRECISION NOT NULL,
    answer_type VARCHAR(20) NOT NULL,
    normative_time_ms BIGINT,
    order_index INTEGER NOT NULL,
    CONSTRAINT fk_questions_topic FOREIGN KEY (topic_id) REFERENCES topics(id)
);

CREATE TABLE IF NOT EXISTS materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT NOT NULL,
    title VARCHAR(500) NOT NULL,
    link VARCHAR(2000) NOT NULL,
    type VARCHAR(20) NOT NULL,
    difficulty_level INTEGER NOT NULL,
    CONSTRAINT fk_materials_topic FOREIGN KEY (topic_id) REFERENCES topics(id)
);

CREATE TABLE IF NOT EXISTS test_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    current_question_index INTEGER NOT NULL,
    finished BOOLEAN NOT NULL,
    mastery_score DOUBLE PRECISION,
    CONSTRAINT fk_test_sessions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_test_sessions_topic FOREIGN KEY (topic_id) REFERENCES topics(id)
);

CREATE TABLE IF NOT EXISTS answer_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_session_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    user_answer CLOB NOT NULL,
    is_correct BOOLEAN NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    response_time_ms BIGINT NOT NULL,
    partial_score DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_answer_results_session FOREIGN KEY (test_session_id) REFERENCES test_sessions(id),
    CONSTRAINT fk_answer_results_question FOREIGN KEY (question_id) REFERENCES questions(id)
);

CREATE INDEX IF NOT EXISTS idx_questions_topic_order
    ON questions(topic_id, order_index);

CREATE INDEX IF NOT EXISTS idx_materials_topic
    ON materials(topic_id);

CREATE INDEX IF NOT EXISTS idx_test_sessions_user_started
    ON test_sessions(user_id, started_at);

CREATE INDEX IF NOT EXISTS idx_test_sessions_topic_started
    ON test_sessions(topic_id, started_at);

CREATE INDEX IF NOT EXISTS idx_answer_results_session
    ON answer_results(test_session_id);
